
---
format:
  revealjs: 
    slide-number: c/t
    progress: true
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: img/dsa.png
    theme: [default, css/index.scss]
    width: 1920
    height: 1080
    margin: 0.05
resources:
  - demo.pdf
---

<h1> Week 2 - August 27 </h1>

<h2> Exploratory Data Analysis for Big Data </h2>

<hr>

<h3> Jeanne McClure, Ph.D </h3>

<h3> DSC 406.001 </h3>
<br>




## Best Practices for Reproducible Research

1.  Document everything!

2.  Everything is a (text) file.

3.  All files should be human readable.

4.  Explicitly tie your files together.

5.  Have a plan to organize, store, and make your files available.

To learn more: [Reproducible research with R and R studio (3rd Edition)](https://github.com/christophergandrud/Rep-Res-Book). CRC Press.

::: notes
Speaker Notes:

1.  **Document everything!** Obviously, in order to reproduce your research, others must be able to know what you did. Documentation of includes, but is not limited to the data itself, analysis code, the write-up of results, and explanations of these files (e.g. data set codebooks, software information, and so on).

2.  **Everything is a (text) file**. Ideally, your documentation will be stored in the simplest file format possible to store this information. Usually the simplest file format is the humble, but versatile, text file. Text files are extremely nimble and can used your data in, like in comma-separated values (CSV) format for example, can contain your analysis code in files, and can be the basis for publishable formats like articles, webpages, books, etc. using markup languages such as Markdown. One reason reproducible research is best stored in text fles is that this helps future-proof your research

3.  **All files should be human readable.** Treat all of your research fles as if someone who has not worked on the project will, in the future, try to understand them. Computer code is a way of communicating with the computer. It is 'machine readable' in that the computer is able to use it to understand what you want to do.2 However, there is a very good chance that other people (or you six months in the future) will not understand what you were telling the computer. So, you need to make all of your files 'human readable'. To make them human readable, you should comment on your code with the goal of communicating its design and purpose.

4.  **Explicitly tie your files together.** Researchers often do not explicitly document the relationships between fles that they used in their research. For example, the results of an analysis--a table or figure--may be copied and pasted into a presentation document. It can be very difficult for future researchers to trace the table or fgure back to a particular statistical model and a particular data set without clear documentation. Therefore, it is important to make the links between your files explicit.

5.  **Have a plan to organize, store, and make your files available**. Finally, in order for independent researchers to reproduce your work, they need to be able access the fles that instruct them how to do this. Files also need to be organized so that independent researchers can fgure out how they ft together. So, from the beginning of your research process, you should have a plan for organizing your files and a way to make them accessible.

**Learn More**

We've only scratched the surface Reproducible Research practices and highlight recommend the book Reproducible research with R and R studio to learn more.
:::
